[package]
name = "satrunner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
log = "0.4"
console_log = { version = "1"}
rand = "0.8.5"
serde = "1.0"

[profile.release]
lto = "thin"
opt-level = 'z'
